/*
    Copyright (C) 2010 LearningWell AB (www.learningwell.com), Kärnkraftsäkerhet och Utbildning AB (www.ksu.se)

    This file is part of GIL (Generic Integration Layer).

    GIL is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    GIL is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with GIL.  If not, see <http://www.gnu.org/licenses/>.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.13 at 11:34:11 AM CEST 
//


package gil.web.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "documentation",
    "parameters"
})
@XmlRootElement(name = "command")
public class Command {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String documentation;
    @XmlElement(required = true)
    protected Command.Parameters parameters;

    /**
     * Searches the array for the given command. Null is returned if not found.
     */
    static public Command find(String commandName, Command[] searchIn) {
        for (Command cd : searchIn) {
            if (commandName.equals(cd.getName()))
                return cd;
        }
        return null;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getDocumentation() {
        return documentation;
    }

    public void setDocumentation(String value) {
        this.documentation = value;
    }

    public Command.Parameters getParameters() {
        return parameters;
    }

    public void setParameters(Command.Parameters value) {
        this.parameters = value;
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameter"
    })
    public static class Parameters {

        @XmlElement(required = true)
        protected List<Command.Parameters.Parameter> parameter;

        /**
         * Gets the value of the parameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Command.Parameters.Parameter }
         * 
         * 
         */
        public List<Command.Parameters.Parameter> getParameter() {
            if (parameter == null) {
                parameter = new ArrayList<Command.Parameters.Parameter>();
            }
            return this.parameter;
        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "mandatory",
            "documentation"
        })
        public static class Parameter {

            @XmlElement(required = true)
            protected String name;
            protected boolean mandatory;
            @XmlElement(required = true)
            protected String documentation;

            public String getName() {
                return name;
            }

            public void setName(String value) {
                this.name = value;
            }

            public boolean isMandatory() {
                return mandatory;
            }

            public void setMandatory(boolean value) {
                this.mandatory = value;
            }

            public String getDocumentation() {
                return documentation;
            }

            public void setDocumentation(String value) {
                this.documentation = value;
            }
        }
    }
}
